//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _29_04_2023
{
    using System;
    using System.Collections.Generic;
    
    public partial class authors_books
    {
        public int id { get; set; }
        public int id_author { get; set; }
        public int id_book { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual books books { get; set; }
    }
}
