//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _29_04_2023
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class libraryEntities : DbContext
    {
        private static libraryEntities instance;
        private libraryEntities()
            : base("name=libraryEntities")
        {
        }
        public static libraryEntities get_instance()
        {
            if (instance == null)
                instance = new libraryEntities();
            return instance;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<authors_books> authors_books { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<readers> readers { get; set; }
        public virtual DbSet<taken_books> taken_books { get; set; }
    }
}
