//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _29_04_2023
{
    using System;
    using System.Linq;

    public partial class taken_books
    {
        public int id { get; set; }
        public int id_reader { get; set; }
        public int id_book { get; set; }
        public System.DateTime receiving { get; set; }
        public System.DateTime should_return { get; set; }
        public Nullable<System.DateTime> fact_return { get; set; }
    
        public virtual books books { get; set; }
        public virtual readers readers { get; set; }
        public string get_reader_name()
        {
            return (from r in libraryEntities.get_instance().readers where r.id == id_reader select r.name).FirstOrDefault();
        }
        public string get_book_name()
        {
            return (from b in libraryEntities.get_instance().books where b.id == id_book select b.name).FirstOrDefault();
        }
    }
}
